[package]
name = "sample_organizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audrey = "0.3.0"
colored = "2.1.0"
rayon = "1.10.0"
sha2 = "0.10.8"
walkdir = "2.5.0"
